name: Deploy Zakupek API

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    environment: production

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t ${{ vars.API_CONTAINER_NAME }} .

    - name: Stop existing container
      run: docker container stop ${{ vars.API_CONTAINER_NAME }} || true

    - name: Remove existing container
      run: docker container rm ${{ vars.API_CONTAINER_NAME }} || true

    - name: Run new container
      run: |
        docker run --detach \
          --name ${{ vars.API_CONTAINER_NAME }} \
          --publish ${{ vars.API_PORT }}:8080 \
          --restart always \
          -e ConnectionStrings__DefaultConnection=${{ secrets.PROD_CONNECTION_STRING }} \
          -e JwtSettings__SecretKey=${{ secrets.PROD_JWT_SECRET }} \
          -e OpenRouter__ApiKey=${{ secrets.PROD_OPENROUTER_API_KEY }} \
          ${{ vars.API_CONTAINER_NAME }}
