name: Deploy Zakupek API

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    environment: production

    steps:
    - uses: actions/checkout@v2

    - name: Create appsettings.Production.json
      working-directory: apps/src/ZakupekApi
      run: |
        echo '{
          "ConnectionStrings": {
            "DefaultConnection": "${{ secrets.PROD_CONNECTION_STRING }}"
          },
          "JwtSettings": {
            "SecretKey": "${{ secrets.PROD_JWT_SECRET }}",
            "Issuer": "ZakupekApi",
            "Audience": "ZakupekApiClients"
          },
          "OpenRouter": {
            "BaseUrl": "https://openrouter.ai/api/v1/",
            "ApiKey": "${{ secrets.PROD_OPENROUTER_API_KEY }}"
          }
        }' > appsettings.Production.json

    - name: Build Docker image
      run: docker build -t ${{ vars.API_CONTAINER_NAME }} -f apps/src/ZakupekApi/Dockerfile .

    - name: Stop existing container
      run: docker container stop ${{ vars.API_CONTAINER_NAME }} || true

    - name: Remove existing container
      run: docker container rm ${{ vars.API_CONTAINER_NAME }} || true

    - name: Run new container
      run: |
        docker run --detach \
          --name ${{ vars.API_CONTAINER_NAME }} \
          --publish ${{ vars.API_PORT }}:8080 \
          --restart always \
          ${{ vars.API_CONTAINER_NAME }}